import type { SdlcPipeline } from "@/lib/schemas/sdlc-pipeline";

function bulletList(items: string[]): string {
  if (items.length === 0) return "_None_";
  return items.map((item) => `- ${item}`).join("\n");
}

export function pipelineToMarkdown(pipeline: SdlcPipeline, title = "SDLC Pipeline Report"): string {
  const { clarifiedRequirement: cr, impactAnalysis: ia, deliveryReadiness: dr } = pipeline;

  const sections = [
    `# ${title}`,
    "",
    `_Generated by AI SDLC Pipeline Assistant_`,
    "",
    "## Clarified Requirement",
    "",
    `**Summary:** ${cr.summary}`,
    "",
    `**User Story:** ${cr.userStory}`,
    "",
    "### Assumptions",
    bulletList(cr.assumptions),
    "",
    "### Open Questions",
    bulletList(cr.openQuestions),
    "",
    "### Out of Scope",
    bulletList(cr.outOfScope),
    "",
    "## Impact Analysis",
    "",
    "### Affected Modules",
    bulletList(ia.affectedModules),
    "",
    "### UI Impact",
    bulletList(ia.ui),
    "",
    "### API Impact",
    bulletList(ia.api),
    "",
    "### Database Impact",
    bulletList(ia.database),
    "",
    "### Security Impact",
    bulletList(ia.security),
    "",
    "### Integrations",
    bulletList(ia.integrations),
    "",
    "### Testing Impact",
    bulletList(ia.testingImpact),
    "",
    "## Implementation Plan",
    "",
    ...pipeline.implementationPlan
      .sort((a, b) => a.sequence - b.sequence)
      .map(
        (task) =>
          `### ${task.sequence}. ${task.title}\n\n${task.description}${
            task.dependencies?.length
              ? `\n\n**Dependencies:** ${task.dependencies.join(", ")}`
              : ""
          }`
      ),
    "",
    "## Test Plan",
    "",
    "### Unit Tests",
    bulletList(pipeline.testPlan.unit),
    "",
    "### API Tests",
    bulletList(pipeline.testPlan.api),
    "",
    "### UI Tests",
    bulletList(pipeline.testPlan.ui),
    "",
    "### Regression Tests",
    bulletList(pipeline.testPlan.regression),
    "",
    "### Negative Tests",
    bulletList(pipeline.testPlan.negative),
    "",
    "### Security Tests",
    bulletList(pipeline.testPlan.security),
    "",
    "## Risk Checklist",
    "",
    ...pipeline.riskChecklist.map(
      (r) =>
        `- **[${r.severity.toUpperCase()} / ${r.category}]** ${r.risk}\n  - _Mitigation:_ ${r.mitigation}`
    ),
    "",
    "## Review Checklist",
    "",
    bulletList(pipeline.reviewChecklist),
    "",
    "## Delivery Readiness",
    "",
    `**Score:** ${dr.score}/100`,
    "",
    `**Status:** ${dr.status.replace(/_/g, " ")}`,
    "",
    `**Confidence:** ${dr.confidence}`,
    "",
    "### Approval Needs",
    bulletList(dr.approvalNeeds),
    "",
    `**Recommendation:** ${dr.recommendation}`,
  ];

  return sections.join("\n");
}
